trigger:
  branches:
    include:
      - main  # Cambia esto al nombre de la rama que desees

pool:
  vmImage: 'windows-latest'  # Usa una imagen compatible

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x.x'  # Ajusta a la versión de .NET que usas
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'  # Ajusta el nombre del proyecto de prueba
    arguments: '--configuration $(buildConfiguration) --no-build --logger trx --results-directory $(System.DefaultWorkingDirectory)/TestResults'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)/TestResults'
    mergeTestResults: true
